# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
#  - package-ecosystem: "nuget" # See documentation for possible values
#    directory: "AhaWebApi" # Location of package manifests
#    schedule:
#      interval: "weekly"

  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "ArtifactoryWebApi" # Location of package manifests
    schedule:
      interval: "weekly"

#  - package-ecosystem: "nuget" # See documentation for possible values
#    directory: "ConfluenceWebApi" # Location of package manifests
#    schedule:
#      interval: "weekly"

#  - package-ecosystem: "nuget" # See documentation for possible values
#    directory: "GerritWebApi" # Location of package manifests
#    schedule:
#      interval: "weekly"

#  - package-ecosystem: "nuget" # See documentation for possible values
#    directory: "GithubWebApi" # Location of package manifests
#    schedule:
#      interval: "weekly"

#  - package-ecosystem: "nuget" # See documentation for possible values
#    directory: "GraphWebApi" # Location of package manifests
#    schedule:
#      interval: "weekly"

#  - package-ecosystem: "nuget" # See documentation for possible values
#    directory: "JenkinsWebApi" # Location of package manifests
#    schedule:
#      interval: "weekly"

#  - package-ecosystem: "nuget" # See documentation for possible values
#    directory: "JiraWebApi" # Location of package manifests
#    schedule:
#      interval: "weekly"

#  - package-ecosystem: "nuget" # See documentation for possible values
#    directory: "NistWebApi" # Location of package manifests
#    schedule:
#      interval: "weekly"

#  - package-ecosystem: "nuget" # See documentation for possible values
#    directory: "SnipeITWebApi" # Location of package manifests
#    schedule:
#      interval: "weekly"

#  - package-ecosystem: "nuget" # See documentation for possible values
#    directory: "TheTVDBWebApi" # Location of package manifests
#    schedule:
#      interval: "weekly"

  
